#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# post-deploy.sh — Single source of truth for deployed addresses
#
# After deploying contracts (via hardhat), this script:
#   1. Reads the deploy manifest (deploy-manifest.json)
#   2. Updates root .env with new addresses
#   3. Regenerates apps/web/.env.local from root .env
#   4. Syncs ABI from compiled artifacts to x402-sdk
#   5. Validates everything matches
#
# Usage:
#   npm run contracts:deploy          # deploys + writes manifest
#   bash scripts/post-deploy.sh       # propagates everything
#
# Or all-in-one:
#   npm run deploy:full
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/deploy-manifest.json"

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()  { echo -e "${CYAN}[post-deploy]${NC} $1"; }
ok()    { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
fail()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# ═══════════════════════════════════════
# Step 0: Check manifest exists
# ═══════════════════════════════════════
if [ ! -f "$MANIFEST" ]; then
  fail "No deploy-manifest.json found. Run 'npm run contracts:deploy' first."
fi

info "Reading deploy manifest..."
NETWORK=$(node -e "console.log(require('$MANIFEST').network)")
CHAIN_ID=$(node -e "console.log(require('$MANIFEST').chainId)")
VERIFIER=$(node -e "console.log(require('$MANIFEST').verifierAddress)")
TOKEN=$(node -e "console.log(require('$MANIFEST').tokenAddress || '')")
TIMESTAMP=$(node -e "console.log(require('$MANIFEST').timestamp)")

echo ""
echo "  Network:     $NETWORK (chain $CHAIN_ID)"
echo "  Verifier:    $VERIFIER"
[ -n "$TOKEN" ] && echo "  MockUSDT0:   $TOKEN"
echo "  Deployed at: $TIMESTAMP"
echo ""

# ═══════════════════════════════════════
# Step 1: Update root .env
# ═══════════════════════════════════════
ENV_FILE="$ROOT/.env"
info "Updating root .env..."

update_env() {
  local key="$1" val="$2" file="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    # Use a temp file for portable sed (macOS + Linux)
    sed "s|^${key}=.*|${key}=${val}|" "$file" > "$file.tmp" && mv "$file.tmp" "$file"
  else
    echo "${key}=${val}" >> "$file"
  fi
}

if [ "$CHAIN_ID" = "71" ]; then
  # Testnet deploy
  update_env "X402_CONTRACT_ADDRESS_TESTNET" "$VERIFIER" "$ENV_FILE"
  update_env "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_TESTNET" "$VERIFIER" "$ENV_FILE"
  if [ -n "$TOKEN" ]; then
    update_env "USDT0_ADDRESS_TESTNET" "$TOKEN" "$ENV_FILE"
    update_env "NEXT_PUBLIC_USDT0_ADDRESS" "$TOKEN" "$ENV_FILE"
  fi
elif [ "$CHAIN_ID" = "1030" ]; then
  # Mainnet deploy
  update_env "X402_CONTRACT_ADDRESS_MAINNET" "$VERIFIER" "$ENV_FILE"
  update_env "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_MAINNET" "$VERIFIER" "$ENV_FILE"
fi
ok "Root .env updated"

# ═══════════════════════════════════════
# Step 2: Regenerate apps/web/.env.local
# ═══════════════════════════════════════
WEB_ENV="$ROOT/apps/web/.env.local"
info "Regenerating apps/web/.env.local from root .env..."

# Extract NEXT_PUBLIC_ vars from root .env (these are what Next.js needs)
extract_env() {
  grep "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2-
}

cat > "$WEB_ENV" << EOF
# ═══════════════════════════════════════════════════════════════
# AUTO-GENERATED by scripts/post-deploy.sh — do not edit manually
# Source of truth: root .env
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ═══════════════════════════════════════════════════════════════
NEXT_PUBLIC_API_BASE=$(extract_env "NEXT_PUBLIC_API_BASE")
NEXT_PUBLIC_FAUCET_URL=$(extract_env "NEXT_PUBLIC_FAUCET_URL")
NEXT_PUBLIC_USDT0_ADDRESS=$(extract_env "NEXT_PUBLIC_USDT0_ADDRESS")
NEXT_PUBLIC_WC_PROJECT_ID=$(extract_env "NEXT_PUBLIC_WC_PROJECT_ID")
NEXT_PUBLIC_X402_CONTRACT_ADDRESS=$(extract_env "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_TESTNET")
NEXT_PUBLIC_X402_CONTRACT_ADDRESS_TESTNET=$(extract_env "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_TESTNET")
NEXT_PUBLIC_X402_CONTRACT_ADDRESS_MAINNET=$(extract_env "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_MAINNET")
NEXT_PUBLIC_NETWORK=$(extract_env "NEXT_PUBLIC_NETWORK" || echo "testnet")
NEXT_PUBLIC_SERVICE_WALLET_ADDRESS=$(extract_env "NEXT_PUBLIC_SERVICE_WALLET_ADDRESS")
NEXT_PUBLIC_SERVICE_WALLET_ADDRESS_2=$(extract_env "NEXT_PUBLIC_SERVICE_WALLET_ADDRESS_2")
EOF

ok "apps/web/.env.local regenerated"

# ═══════════════════════════════════════
# Step 3: Sync ABI to x402-sdk
# ═══════════════════════════════════════
ARTIFACT="$ROOT/packages/contracts/artifacts/contracts/X402PaymentVerifier.sol/X402PaymentVerifier.json"
SDK_ABI="$ROOT/packages/x402-sdk/src/abi.ts"

if [ -f "$ARTIFACT" ]; then
  info "Syncing ABI from compiled artifact to x402-sdk..."
  node -e "
    const artifact = require('$ARTIFACT');
    const abi = JSON.stringify(artifact.abi, null, 2);
    const content = 'export const verifierAbi = ' + abi + ' as const;\\n';
    require('fs').writeFileSync('$SDK_ABI', content);
  "
  ok "x402-sdk/src/abi.ts synced from compiled artifact"

  # Rebuild the SDK so dist/ matches the new ABI
  info "Rebuilding x402-sdk (dist/)..."
  (cd "$ROOT" && npm run build -w packages/x402-sdk 2>&1) || warn "SDK build failed — run 'npm run build -w packages/x402-sdk' manually"
  ok "x402-sdk dist/ rebuilt"
else
  warn "No compiled artifact found at $ARTIFACT — skipping ABI sync"
  warn "Run 'npm run contracts:compile' first"
fi

# ═══════════════════════════════════════
# Step 4: Mint agent tokens (testnet only)
# ═══════════════════════════════════════
if [ "$CHAIN_ID" = "71" ] && [ -n "$TOKEN" ]; then
  AGENT_KEY=$(grep "^AGENT_PRIVATE_KEY=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2-)
  if [ -n "$AGENT_KEY" ] && [ "$AGENT_KEY" != "0x" ]; then
    info "Minting 100 USDT0 to agent wallet (testnet)..."
    (cd "$ROOT" && npx tsx scripts/mint-agent-tokens.ts 2>&1) && ok "Agent wallet funded with 100 USDT0" || warn "Agent token minting failed — run 'npx tsx scripts/mint-agent-tokens.ts' manually"
  else
    warn "No AGENT_PRIVATE_KEY in .env — skipping agent token mint"
  fi
fi

# ═══════════════════════════════════════
# Step 5: Validate consistency
# ═══════════════════════════════════════
info "Validating address consistency..."
ERRORS=0

check_match() {
  local label="$1" expected="$2" file="$3" key="$4"
  local actual
  actual=$(grep "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- || echo "")
  if [ -z "$actual" ]; then
    warn "$label: $key not found in $file"
    ERRORS=$((ERRORS + 1))
  elif [ "$(echo "$actual" | tr '[:upper:]' '[:lower:]')" != "$(echo "$expected" | tr '[:upper:]' '[:lower:]')" ]; then
    echo -e "  ${RED}MISMATCH${NC} $label"
    echo "    Expected: $expected"
    echo "    Actual:   $actual"
    echo "    File:     $file"
    ERRORS=$((ERRORS + 1))
  fi
}

if [ "$CHAIN_ID" = "71" ]; then
  check_match "Verifier (root)" "$VERIFIER" "$ENV_FILE" "X402_CONTRACT_ADDRESS_TESTNET"
  check_match "Verifier (web)" "$VERIFIER" "$WEB_ENV" "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_TESTNET"
  if [ -n "$TOKEN" ]; then
    check_match "Token (root)" "$TOKEN" "$ENV_FILE" "USDT0_ADDRESS_TESTNET"
    check_match "Token (root NEXT_PUBLIC)" "$TOKEN" "$ENV_FILE" "NEXT_PUBLIC_USDT0_ADDRESS"
    check_match "Token (web)" "$TOKEN" "$WEB_ENV" "NEXT_PUBLIC_USDT0_ADDRESS"
  fi
elif [ "$CHAIN_ID" = "1030" ]; then
  check_match "Verifier (root)" "$VERIFIER" "$ENV_FILE" "X402_CONTRACT_ADDRESS_MAINNET"
  check_match "Verifier (web)" "$VERIFIER" "$WEB_ENV" "NEXT_PUBLIC_X402_CONTRACT_ADDRESS_MAINNET"
fi

echo ""
if [ "$ERRORS" -gt 0 ]; then
  fail "$ERRORS address mismatches found!"
else
  ok "All addresses consistent across .env files"
fi

# ═══════════════════════════════════════
# Summary
# ═══════════════════════════════════════
echo ""
echo "═══════════════════════════════════════"
echo "  POST-DEPLOY COMPLETE"
echo "═══════════════════════════════════════"
echo ""
echo "  Updated files:"
echo "    - .env"
echo "    - apps/web/.env.local"
[ -f "$ARTIFACT" ] && echo "    - packages/x402-sdk/src/abi.ts"
echo ""
echo "  Next steps:"
echo "    1. Restart dev servers (Ctrl+C, then npm run dev:api:local)"
echo "    2. Restart web (npm run dev:web)"
echo "    3. Verify in browser: token addresses should match"
echo ""
