// Code generated by @wagmi/cli via `pnpm contracts:generate` — DO NOT EDIT.
// Source: conflux-contracts/wagmi.config.ts → artifacts/contracts/
//
// Re-exports the generated type-safe ABI + bytecode constants under the
// legacy UPPER_CASE names used throughout the SDK and CAS worker, and also
// under wagmi/viem-idiomatic camelCase names for forward-looking usage.

// ─── ABIs ─────────────────────────────────────────────────────────────────────
export {
  automationManagerAbi as AUTOMATION_MANAGER_ABI,
  swappiPriceAdapterAbi as SWAPPI_PRICE_ADAPTER_ABI,
  permitHandlerAbi as PERMIT_HANDLER_ABI,
  automationManagerAbi,
  swappiPriceAdapterAbi,
  permitHandlerAbi,
} from './generated.js';

// ─── Deployment bytecode ──────────────────────────────────────────────────────
export {
  automationManagerBytecode,
  swappiPriceAdapterBytecode,
  permitHandlerBytecode,
} from './generated.js';

// ─── Deployed addresses (baked in at codegen time from deployments.json) ──────
// automationManagerAddress = { 1030: '0x...', 71?: '0x...' } as const
export {
  automationManagerAddress,
  automationManagerConfig,
  swappiPriceAdapterAddress,
  swappiPriceAdapterConfig,
  permitHandlerAddress,
  permitHandlerConfig,
} from './generated.js';
